### ISSUE TITLE
Cannot connect to Database using ssl

### ISSUE THREAD

**Issue by christk1** [jtv/libpqxx#675]
I am trying to connect to my rds database instance from my fargate service using `libpqxx` library in c++ but i am unable to do so.
the log on the rds side is:

`2023-04-20 11:40:40 UTC:10.10.2.103(46582):[unknown]@[unknown]:[1939]:LOG: could not accept SSL connection: EOF detected`

the code is:

```
  try {
    const auto dbConnString1 =
        "host=cdk-rds-postgresdb7ff341c6... "
        "dbname=SB_Database "
        "user=database_user "
        "password=passss "
        "port=5432 "
        "sslrootcert=/etc/ssl/certs "
        "sslmode=verify-full";
    pqxx::connection conn(dbConnString1);
    std::cout << "Connected to the PostgreSQL database." << std::endl;
  } catch (const std::exception& e) {
    std::cerr << "Error: " << e.what() << std::endl;
    return 1;
  }
```
log on the c++:
```
Error: connection to server at "cdk-rds-postgresdb7ff341c6..." (10.10.4.24), port 5432 failed: could not create SSL context: malloc failure
```
I tried to connect with a python app using `psycopg2-binary` and I Successfully connect to the db with the same configuration and without specifying the `sslrootcert` and `sslmode` fields.

the docker image I am using for my c++ container is: `debian:bookworm-slim` with `ca-certificates` installed while for the python app, I am using `python:3.9-slim-buster`

Any help would be much appreciated!

**Comment by tt4g** [comment]
"could not create SSL context: malloc failure" seems to be an OpenSSL error message.
Would using a different Docker image or changing the OpenSSL version solve the problem?

**Comment by KayEss** [comment]
If malloc is returning NULL there's something fairly seriously wrong, most likely with the memory configuration of your docker instance. You should check how much RAM is available to the instance and how much it uses when you try to run.

**Comment by christk1** [comment]
@tt4g , @KayEss  Thank you for your suggestions, tried both with no success. Passing the `sslmode=required` gives me the: `Error: invalid sslmode value: "required"`. Therefore I can understand that there is something wrong with the openssl not enabled in the library.
That's how I enable the library in my cmake project:
```
FetchContent_Declare(
	libpqxx 
  GIT_REPOSITORY https://github.com/jtv/libpqxx.git
	GIT_TAG master
	SOURCE_DIR ${PROJECT_SOURCE_DIR}/third_party/libpqxx
	BINARY_DIR ${PROJECT_BINARY_DIR}/third_party/libpqxx
)

FetchContent_GetProperties(libpqxx)

if (NOT libpqxx_POPULATE)
    FetchContent_Populate(libpqxx)
    add_subdirectory(${libpqxx_SOURCE_DIR} ${libpqxx_BINARY_DIR})
endif()
```
Do you know if I need to declare something in order to compile with openssl option?

**Comment by tt4g** [comment]
`sslmode=required` is wrong `sslmode=require` is correct.
but `sslmode=verify-ca` is better.

Quote: https://www.postgresql.org/docs/15/libpq-ssl.html

> **Note**
> For backwards compatibility with earlier versions of PostgreSQL, if a root CA file exists, the behavior of sslmode=require will be the same as that of verify-ca, meaning the server certificate is validated against the CA. Relying on this behavior is discouraged, and applications that need certificate validation should always use verify-ca or verify-full.

And it is libpq's role to establish SSL connections using OpenSSL.
If there is a problem, it is the build of libpq.

**Comment by jtv** [comment]
As far as libpqxx is concerned, you don't need to include the openssl headers in your project.  (Or even the libpq headers — though of course the libpq build does need them.)

**Comment by christk1** [comment]
Managed to connect to the aws db while running the app locally. Some package is missing from the image that I am using to connect. The following packages are installed:
```
RUN apt-get update && apt-get install -y \
    ca-certificates \
    build-essential \
    libasio-dev \
    libpq-dev \
    postgresql-server-dev-all \
    zlib1g-dev \
    libssl-dev \
    git \
    wget
```
if anything is missing please let me know

**Comment by tt4g** [comment]
> Maybe postgresql-client-14 needs to be installed too but I need to test it

As far as Debian packages are concerned, the provided libpq version is 15.
https://packages.debian.org/bookworm/database/

**Comment by christk1** [comment]
Update: the docker image doesn't need anything else. I tested my app while running it from inside the container locally and it connected to the database. The problem is while running this in the fargate service in AWS and only when I run the c++ app. The python one is working. I suppose that something is happening about timeouts in the connection or a similar thing

**Comment by jtv** [comment]
> Update: the docker image doesn't need anything else. I tested my app while running it from inside the container locally and it connected to the database. The problem is while running this in the fargate service in AWS and only when I run the c++ app. The python one is working. I suppose that something is happening about timeouts in the connection or a similar thing

FWIW if the python app uses psycopg, that is built on top of libpq just like libpqxx is.  So all the _code_ relating to this problem should be the same.

**Comment by christk1** [comment]
Update 2:
used the same code in cpp and it worked:
```
#include "main.h"

int main()
{
  try
  {
    const auto dbConnString1 =
        "host=cdk-rds-postgresdb7ff341c6-... "
        "dbname=SB_Database "
        "user=database_user "
        "password=... "
        "port=5432 "
        "sslmode=verify-ca "
        "sslrootcert=ap-northeast-1-bundle.pem";

    std::cout << "connection string: " << dbConnString1 << std::endl;
    pqxx::connection conn(dbConnString1);
    std::cout << "Connected to the PostgreSQL database." << std::endl;
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error: " << e.what() << std::endl;
    return 1;
  }
  crow::SimpleApp app;

  CROW_ROUTE(app, "/")
  ([]()
   { return "Hello world"; });

  app.bindaddr("0.0.0.0").port(8080).run();
}
```
My real project is using OpenSSL to compute sha256 etc.. I found [this](https://github.com/jtv/libpqxx/issues/192#issuecomment-501724530) issue, maybe its related to this?

CC @jtv

**Comment by jtv** [comment]
> Update 2: used the same code in cpp and it worked:
> 
> ```
> #include "main.h"
> 
> int main()
> {
>   try
>   {
>     const auto dbConnString1 =
>         "host=cdk-rds-postgresdb7ff341c6-... "
>         "dbname=SB_Database "
>         "user=database_user "
>         "password=... "
>         "port=5432 "
>         "sslmode=verify-ca "
>         "sslrootcert=ap-northeast-1-bundle.pem";
> 
>     std::cout << "connection string: " << dbConnString1 << std::endl;
>     pqxx::connection conn(dbConnString1);
>     std::cout << "Connected to the PostgreSQL database." << std::endl;
>   }
>   catch (const std::exception &e)
>   {
>     std::cerr << "Error: " << e.what() << std::endl;
>     return 1;
>   }
>   crow::SimpleApp app;
> 
>   CROW_ROUTE(app, "/")
>   ([]()
>    { return "Hello world"; });
> 
>   app.bindaddr("0.0.0.0").port(8080).run();
> }
> ```
> 
> My real project is using OpenSSL to compute sha256 etc.. I found [this](https://github.com/jtv/libpqxx/issues/192#issuecomment-501724530) issue, maybe its related to this?

Based on the documentation I wouldn't expect so.  `PQinitOpenSSL` is a bit of a misnomer — it's for _preventing_ initialisation of those libraries.  It becomes relevant when your application (or some other library in it) also initialises either of them.

**Comment by KayEss** [comment]
> maybe its related to this?

I just implemented TLS support in another library a few months and looked into the initialisation. It is now reference counted, so as long as each library initialises things the same number of times everything will be fine, so I don't think that's the problem

**Comment by tt4g** [comment]
Have you confirmed that access to RDS is allowed from the Fargate container?

It is recommended to check if you can connect to RDS without SSL.
If you cannot access it, then the container access is not allowed and you are missing AWS settings changes.

**Comment by jtv** [comment]
It really shouldn't make any difference here, but I just sketched out a branch to support `PQinitOpenSSL` in #678.

If anyone's got any ideas on how to write a good automated test for this, preferably without doing too much work, I'd love to hear it!

**Comment by christk1** [comment]
Tried with this branch but still having the same problem. Investigated more and I am using [aws-sdk-cpp](https://github.com/aws/aws-sdk-cpp) library to retrieve some secrets from the AWS account. The strange thing is that if I remove code related to AWS my application is working correctly. Below you can find the code related to AWS.

```
using namespace Aws;

AwsSdkHandler::AwsSdkHandler() : region_{supp::GetEnv("AWS_REGION")} {
#ifdef DEBUG
  options_.loggingOptions.logLevel = Utils::Logging::LogLevel::Debug;
#endif
  InitAPI(options_);
}

AwsSdkHandler::~AwsSdkHandler() { ShutdownAPI(options_); }

rapidjson::Document AwsSdkHandler::getSecret(const Aws::String &secret_id) {
  rapidjson::Document doc;

  Aws::Client::ClientConfiguration config;
  if (!region_.empty()) {
    config.region = region_;
  }

  SecretsManager::SecretsManagerClient sm_client(config);

  // String secretId = "prod/github/token";
  SecretsManager::Model::GetSecretValueRequest request;
  request.SetSecretId(secret_id);

  auto getSecretValueOutcome = sm_client.GetSecretValue(request);
  if (getSecretValueOutcome.IsSuccess()) {
    auto secretString =
        getSecretValueOutcome.GetResult().GetSecretString().c_str();

    if (doc.Parse(secretString).HasParseError())
      fmt::print(
          "AwsSdkHandler::getSecret: failed\n Error code: {}\n Error message: "
          "{}\n\n",
          static_cast<std::uint32_t>(doc.GetParseError()),
          rapidjson::GetParseError_En(doc.GetParseError()));
  } else
    std::cout << "AwsSdkHandler::getSecret: Failed with Error: "
              << getSecretValueOutcome.GetError() << std::endl;

  // check:  (doc.GetType() == rapidjson::kNullType) || doc.HasParseError()
  return doc;
}
```
and calling it like that:
```
  const char* secretId = std::getenv("SECRET_ID");
  rapidjson::Document credentialsJson;
  {
    AwsSdkHandler awsSdkHandler;
    credentialsJson = awsSdkHandler.getSecret(secretId);
  }
```
I think that the problem lies in calling `InitAPI`. It probably makes c initialisations that affect the libpqxx library

**Comment by tt4g** [comment]
It appears that `InitAPI()` and `ShutdownAPI()` must be called once each in the application and are not thread-safe (aws/aws-sdk-cpp#456).
Are you calling these APIs more than once?

**Comment by jtv** [comment]
Ah, if you're also doing other things in the application that also invoke the openssl or crypto libraries, then library initialisation does become an issue.

Try the branch in #678, and call `pqxx::do_not_initialize_ssl` before making the database connection.  I'm not sure whether you'd need to pass `pqxx::skip_init::openssl`, or `pqxx::skip_init::crypto`, or both.  My guess is both.  (Pass them as separate arguments.)

**Comment by christk1** [comment]
> 

What I did was calling `pqxx::internal::do_not_initialize_ssl(1);` before the AWS call and after the AWS code, o opened the db connection, was this wrong?

**Comment by christk1** [comment]
> Ah, if you're also doing other things in the application that also invoke the openssl or crypto libraries, then library initialisation does become an issue.
> 
> Try the branch in #678, and call `pqxx::do_not_initialize_ssl` before making the database connection. I'm not sure whether you'd need to pass `pqxx::skip_init::openssl`, or `pqxx::skip_init::crypto`, or both. My guess is both. (Pass them as separate arguments.)

What I did was calling pqxx::internal::do_not_initialize_ssl(1); before the AWS call and after the AWS code, o opened the db connection, was this wrong?

**Comment by jtv** [comment]
> > Ah, if you're also doing other things in the application that also invoke the openssl or crypto libraries, then library initialisation does become an issue.
> > Try the branch in #678, and call `pqxx::do_not_initialize_ssl` before making the database connection. I'm not sure whether you'd need to pass `pqxx::skip_init::openssl`, or `pqxx::skip_init::crypto`, or both. My guess is both. (Pass them as separate arguments.)
> 
> What I did was calling `pqxx::internal::do_not_initialize_ssl(1);` before the AWS call and after the AWS code, I opened the db connection, was this wrong?

Ah no, not the function in `pqxx::internal` -- those are... internal.  :-D

The other function I added in `pqxx/connection.hxx`, that's directly in `pqxx`.

**Comment by christk1** [comment]
Final update:
chose to drop aws-sdk-cpp library and provided the secrets to my container through cdk securely. Thank you all for your time :)

**Comment by jake-007** [comment]
This is an issue somewhere between libpq and openssl as discussed e.g. [here](https://github.com/Homebrew/homebrew-core/issues/155651). There is some incompatibility between libpq and openssl v. 3.2. Downgrading openssl to v. 3.1.4 is the solution. Using vcpkg, I implemented it as follows:

_vcpkg.json_:
```json
{
  "name": "dbtest",
  "version-string": "1.0.0",
  "builtin-baseline": "215a2535590f1f63788ac9bd2ed58ad15e6afdff",
  "dependencies": [
    {
      "name": "libpq",
      "features": [
        "openssl"
      ]
    }
  ],
  "overrides": [
    {
      "name": "libpq",
      "version-string": "16.2#1"
    },
    {
      "name": "openssl",
      "version-string": "3.1.4#1"
    }
  ]
}
```

**Comment by jtv** [comment]
Thanks very much @jak!  I hope that solves the problem.
